version: '3.8'

services:
  web:
    image: webdevops/php-apache-dev:latest
    volumes:
      - ./src:/app
    ports:
      - "8080:80"
    networks:
      app-network:
        ipv4_address: 172.28.1.2

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24
